"""add DocumentDirectory

Revision ID: ea32ab02f888
Revises: 8782057ff0dc
Create Date: 2024-08-18 07:26:23.108276

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea32ab02f888'
down_revision = '8782057ff0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embition_document_directories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', models.types.StringUUID(), nullable=False),
    sa.Column('document_id', models.types.StringUUID(), nullable=False),
    sa.Column('dir_path', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id', name='document_directories_pkey')
    )
    with op.batch_alter_table('embition_document_directories', schema=None) as batch_op:
        batch_op.create_index('document_directories_dataset_id_idx', ['dataset_id'], unique=False)
        batch_op.create_index('document_directories_dir_path_idx', ['dir_path'], unique=False)
        batch_op.create_index('document_directories_document_id_idx', ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embition_document_directories', schema=None) as batch_op:
        batch_op.drop_index('document_directories_document_id_idx')
        batch_op.drop_index('document_directories_dir_path_idx')
        batch_op.drop_index('document_directories_dataset_id_idx')

    op.drop_table('embition_document_directories')
    # ### end Alembic commands ###
